repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # 這個可以根據你的專案需求變更
    hooks:
      - id: end-of-file-fixer
        enabled: false  # 停用 EOF 修正
      - id: trailing-whitespace
        enabled: false  # 停用空白修正

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0  # 選擇適合你的版本
    hooks:
      - id: yamllint
        args: ["--config-data", "{extends: default, rules: {trailing-spaces: disable, new-line-at-end-of-file: disable}}"]
